let album1 = {
  "title": "A Night at the Opera",
  "genre": "Rock",
  "songs": [
    "Death on Two Legs",
    "Lazing on a Sunday Afternoon",
    "I'm in Love with My Car",
    "You're My Best Friend",
    "'39",
    "Sweet Lady",
    "Seaside Rendezvous",
    "The Prophet's Song",
    "Love of My Life",
    "Good Company",
    "Bohemian Rhapsody",
    "God Save the Queen",
  ],
  "cover": "Cover Image URL",
  "year": 1975,
  "length": 43.08,
  "artist": "Queen",
  "producer": "Roy Thomas Baker and Queen",
  "label": "EMI Records and Elektra Records",
  "description":
    "Este álbum es ampliamente considerado como uno de los mejores trabajos de Queen y uno de los mejores álbumes de rock de todos los tiempos. Fue el álbum más caro jamás producido en ese momento y presentó una amplia gama de estilos musicales, desde baladas y ópera hasta hard rock y heavy metal.",
};
let album2 = {
  "title": "Ramones",
  "genre": "Punk rock",
  "songs": [
    "Blitzkrieg Bop",
    "Beat on the Brat",
    "Judy Is a Punk",
    "I Wanna Be Your Boyfriend",
    "Chain Saw",
    "Now I Wanna Sniff Some Glue",
    "I Don't Wanna Go Down to the Basement",
    "Loudmouth",
    "Havana Affair",
    "Listen to My Heart",
    "53rd & 3rd",
    "Let's Dance",
    "I Don't Wanna Walk Around With You",
    "Today Your Love, Tomorrow the World",
  ],
  "cover": "Cover Image URL",
  "year": 1976,
  "length": 29.04,
  "artist": "The Ramones",
  "producer": "Craig Leon",
  "label": "Sire Records",
  "description":
    "Este álbum debut homónimo es considerado uno de los primeros álbumes punk y ayudó a establecer el sonido del punk rock. Las canciones son cortas, rápidas y directas, con letras simples y pegadizas.",
};

let album3 = {
  "title": "Graceland",
  "genre": ["Worldbeat", "Pop", "Folk"],
  "songs": [
    "The Boy in the Bubble",
    "Graceland",
    "I Know What I Know",
    "Gumboots",
    "Diamonds on the Soles of Her Shoes",
    "You Can Call Me Al",
    "Under African Skies",
    "Homeless",
    "Crazy Love, Vol. II",
    "That Was Your Mother",
    "All Around the World or The Myth of Fingerprints",
  ],
  "cover": "Cover Image URL",
  "year": 1986,
  "length": 43.18,
  "artist": "Paul Simon",
  "producer": "Paul Simon",
  "label": "Warner Bros. Records",
  "description":
    "Este álbum fue un gran éxito comercial y crítico para Paul Simon y presentó una fusión única de música pop, rock y worldbeat. Simon colaboró con músicos sudafricanos en el álbum y ayudó a popularizar la música sudafricana en todo el mundo.",
};
let album4 = {
  "title": "The Rise and Fall of Ziggy Stardust and the Spiders from Mars",
  "genre": "Rock",
  "songs": [
    "Five Years",
    "Soul Love",
    "Moonage Daydream",
    "Starman",
    "It Ain't Easy",
    "Lady Stardust",
    "Star",
    "Hang On to Yourself",
    "Ziggy Stardust",
    "Suffragette City",
    "Rock 'n' Roll Suicide",
  ],
  "cover": "Cover Image URL",
  "year": 1972,
  "length": 38.29,
  "artist": "David Bowie",
  "producer": "Ken Scott, David Bowie",
  "label": "RCA Records",
  "description":
    "Este álbum conceptual cuenta la historia del personaje ficticio Ziggy Stardust, un extraterrestre que viene a la Tierra para presentar un mensaje de esperanza en medio del desespero. El álbum es ampliamente considerado como uno de los mejores trabajos de Bowie y ayudó a establecerlo como una figura importante en la música rock.",
};
let album5 = {
  "title": "Thriller",
  "genre": ["Pop", "Funk"],
  "songs": [
    "Wanna Be Startin' Somethin'",
    "Baby Be Mine",
    "The Girl Is Mine",
    "Thriller",
    "Beat It",
    "Billie Jean",
    "Human Nature",
    "P.Y.T. (Pretty Young Thing)",
    "The Lady in My Life",
  ],
  "cover": "Cover Image URL",
  "year": 1982,
  "length": 42.19,
  "artist": "Michael Jackson",
  "producer": "Quincy Jones, Michael Jackson",
  "label": "Epic Records",
  "description":
    "Este álbum es uno de los más vendidos de todos los tiempos y presentó una mezcla única de pop, post-disco, R&B, rock y funk. El álbum produjo siete sencillos top 10 y ayudó a establecer a Michael Jackson como una superestrella mundial.",
};
let album6 = {
  "title": "What's Going On",
  "genre": "Soul",
  "songs": [
    "What's Going On",
    "What's Happening Brother",
    "Flyin' High (In the Friendly Sky)",
    "Save the Children",
    "God Is Love",
    "Mercy Mercy Me (The Ecology)",
    "Right On",
    "Wholy Holy",
    "Inner City Blues (Make Me Wanna Holler)",
  ],
  "cover": "Cover Image URL",
  "year": 1971,
  "length": 35.38,
  "artist": "Marvin Gaye",
  "producer": "Marvin Gaye",
  "label": "Tamla",
  "description":
    "Este álbum es ampliamente considerado como uno de los mejores trabajos de Marvin Gaye y presenta una mezcla única de soul, R&B y jazz. El álbum fue un gran éxito comercial y crítico y presentó una fuerte crítica social sobre temas como la guerra, la pobreza y la injusticia racial.",
};
let album7 = {
  "title": "Pet Sounds",
  "genre": "Pop",
  "songs": [
    "Wouldn't It Be Nice",
    "You Still Believe in Me",
    "That's Not Me",
    "Don't Talk (Put Your Head on My Shoulder)",
    "I'm Waiting for the Day",
    "Let's Go Away for Awhile",
    "Sloop John B",
    "God Only Knows",
    "I Know There's an Answer",
    "Here Today",
    "I Just Wasn't Made for These Times",
    "Pet Sounds",
    "Caroline, No",
  ],
  "cover": "Cover Image URL",
  "year": 1966,
  "length": 36.25,
  "artist": "The Beach Boys",
  "producer": "Brian Wilson",
  "label": "Capitol Records",
  "description":
    "Este álbum es ampliamente considerado como uno de los mejores trabajos de The Beach Boys y uno de los mejores álbumes pop/rock de todos los tiempos. Presenta una producción sofisticada e innovadora y una mezcla única de pop barroco, rock psicodélico y música experimental.",
};
let album8 = {
  "title": "Abbey Road",
  "genre": "Rock",
  "songs": [
    "Come Together",
    "Something",
    "Maxwell's Silver Hammer",
    "Oh! Darling",
    "Octopus's Garden",
    "I Want You (She's So Heavy)",
    "Here Comes the Sun",
    "Because",
    "You Never Give Me Your Money",
    "Sun King",
    "Mean Mr. Mustard",
    "Polythene Pam",
    "She Came In Through the Bathroom Window",
    "Golden Slumbers",
    "Carry That Weight",
    "The End",
    "Her Majesty",
  ],
  "cover": "Cover Image URL",
  "year": 1969,
  "length": 47.23,
  "artist": "The Beatles",
  "producer": "George Martin",
  "label": "Apple Records",
  "description":
    "Este fue el último álbum grabado por The Beatles (aunque “Let It Be” fue lanzado después) y presenta una mezcla única de rock, pop, blues y música clásica. El lado B del álbum presenta una larga medley compuesta por varias canciones cortas que se entrelazan entre sí.",
};
let album9 = {
  "title": "Songs in the Key of Life",
  "genre": ["R&B", "Soul"],
  "songs": [
    "Love's in Need of Love Today",
    "Have a Talk with God",
    "Village Ghetto Land",
    "Contusion",
    "Sir Duke",
    "I Wish",
    "Knocks Me Off My Feet",
    "Pastime Paradise",
    "Summer Soft",
    "Ordinary Pain",
    "Isn't She Lovely?",
    "Joy Inside My Tears",
    "Black Man",
    "Ngiculela - Es Una Historia - I Am Singing",
    "If It's Magic",
    "As",
    "Another Star",
    "Saturn",
    "Ebony Eyes",
    "All Day Sucker",
    "Easy Goin' Evening (My Mama's Call)",
  ],
  "cover": "Cover Image URL",
  "year": 1976,
  "length": 104.29,
  "artist": "Stevie Wonder",
  "producer": "Stevie Wonder",
  "label": "Tamla Records",
  "description":
    "Este álbum doble es ampliamente considerado como uno de los mejores trabajos de Stevie Wonder y presenta una amplia gama de estilos musicales, desde R&B y soul hasta pop y jazz. El álbum fue un gran éxito comercial y crítico y ganó varios premios Grammy.",
};
let album10 = {
  "title": "The Wall",
  "genre": "Rock",
  "songs": [
    "In the Flesh?",
    "The Thin Ice",
    "Another Brick in the Wall, Part 1",
    "The Happiest Days of Our Lives",
    "Another Brick in the Wall, Part 2",
    "Mother",
    "Goodbye Blue Sky",
    "Empty Spaces",
    "Young Lust",
    "One of My Turns",
    "Don't Leave Me Now",
    "Another Brick in the Wall, Part 3",
    "Goodbye Cruel World",
    "Hey You",
    "Is There Anybody Out There?",
    "Nobody Home",
    "Vera",
    "Bring the Boys Back Home",
    "Comfortably Numb",
    "The Show Must Go On",
    "In the Flesh",
    "Run Like Hell",
    "Waiting for the Worms",
    "Stop",
    "The Trial",
    "Outside the Wall",
  ],
  "cover": "Cover Image URL",
  "year": 1979,
  "length": 80.42,
  "artist": "Pink Floyd",
  "producer": ["Bob Ezrin", "David Gilmour", "James Guthrie", "Roger Waters"],
  "label": ["Harvest / EMI", "Columbia / CBS Records"],
  "description":
    "Este álbum doble es una ópera rock que cuenta la historia del personaje ficticio Pink, una estrella del rock desencantada cuyo aislamiento autoimpuesto forma un muro metafórico. El álbum fue un gran éxito comercial y crítico y ha sido aclamado como uno de los mejores trabajos de Pink Floyd.",
};
let album11 = {
  "title": "It Takes a Nation of Millions to Hold Us Back",
  "genre": ["Hip hop", "Rap"],
  "songs": [
    "Countdown to Armageddon",
    "Bring the Noise",
    "Don't Believe the Hype",
    "Cold Lampin' with Flavor",
    "Terminator X to the Edge of Panic",
    "Mind Terrorist",
    "Louder than a Bomb",
    "Caught, Can We Get a Witness?",
    "Show 'Em Whatcha Got",
    "She Watch Channel Zero?!",
    "Night of the Living Baseheads",
    "Black Steel in the Hour of Chaos",
    "Security of the First World",
    "Rebel Without a Pause",
    "Prophets of Rage",
    "Party for Your Right to Fight",
  ],
  "cover": "Cover Image URL",
  "year": 1988,
  "length": 57.51,
  "artist": "Public Enemy",
  "producer": ["Chuck D", "Rick Rubin", "Hank Shocklee"],
  "label": ["Def Jam", "Columbia Records"],
  "description":
    "Este álbum es considerado uno de los más influyentes y grandes álbumes de hip-hop de todos los tiempos. Fue producido por The Bomb Squad y lanzado en 1988 a través de Def Jam Recordings. El grupo se propuso crear el equivalente hip-hop del álbum clásico de Marvin Gaye “What’s Going On” (1971), un álbum conocido por su fuerte comentario social. A través de su equipo de producción The Bomb Squad, Public Enemy introdujo un sonido densamente agresivo influenciado por el free jazz, el funk pesado y la musique concrète como telón de fondo para el rapero principal Chuck D, quien empleó retórica sociopolítica, actitudes revolucionarias y vocabulario denso en sus actuaciones.",
};
let album12={
  "title": "Sticky Fingers",
  "genre": ["Rock"],
  "songs": [
    "Brown Sugar",
    "Sway",
    "Wild Horses",
    "Can't You Hear Me Knocking",
    "You Gotta Move",
    "Bitch",
    "I Got the Blues",
    "Sister Morphine",
    "Dead Flowers",
    "Moonlight Mile"
  ],
  "cover": "Cover Image URL",
  "year": 1971,
  "length": 46.25,
  "artist": "The Rolling Stones",
  "producer": "Jimmy Miller",
  "label": "Rolling Stones Records, Atlantic Records and Virgin Records",
  "description":
    "Sticky Fingers es el noveno álbum de estudio de la banda de rock británica The Rolling Stones, publicado en abril de 1971. Fue producido por el estadounidense Jimmy Miller y cuenta por primera vez con la participación íntegra del guitarrista Mick Taylor como miembro de los Stones. También fue el primer disco editado por el sello discográfico del grupo, Rolling Stones Records. Sticky Fingers contiene los sonidos clásicos de rock and roll, country, blues y rhythm and blues que la agrupación inglesa había empleado en sus trabajos anteriores, pero se diferencia de estos al incluir letras más oscuras que hacen referencia a la esclavitud, el sexo interracial y el uso de drogas [^1^][2]."
};